authors: [Orion User 1]
dependencies: {}
description: a collection with some deps on other collections
license: [GPL-3.0-or-later]
name: eos
namespace: arista
readme: README.md
repository: http://github.example.com/orionuser1/skeleton
tags: [tools]
version: 4.1.2
